### ISSUE TITLE
readr dependency

### ISSUE THREAD

**Issue by md-1973** [a-jone5/ddspWQ#1]
Just having to re-install ddspWQ in an RStudio project using renv. Unable to install, message: 
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : there is no package called 'readr'
But readr is very definitely installed and available!

**Comment by md-1973** [comment]
@a-jone5

**Comment by a-jone5** [comment]
@md-1973 a couple of things I'd try from experience.
Start a new session - ensure you don't have an .Rdata file loading up a previous workspace.
check the lock file. 
if they don't work try installing without using renv, then once installed take a new snapshot.

Any of that work?

**Comment by md-1973** [comment]
Good ideas! In the meantime I managed it by a convoluted path of installing with pak - that didn't give an error message. So everything OK for now.
